/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransacoesRouteImport } from './routes/app/transacoes'
import { Route as AppRelatoriosRouteImport } from './routes/app/relatorios'
import { Route as AppPatrimonioRouteImport } from './routes/app/patrimonio'
import { Route as AppMetasRouteImport } from './routes/app/metas'
import { Route as AppFluxoRouteImport } from './routes/app/fluxo'
import { Route as AppDividasRouteImport } from './routes/app/dividas'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppContasRouteImport } from './routes/app/contas'
import { Route as AppConquistasRouteImport } from './routes/app/conquistas'
import { Route as AppCartoesRouteImport } from './routes/app/cartoes'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPatrimonioRoute = AppPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoRoute = AppFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => AppRoute,
} as any)
const AppDividasRoute = AppDividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppConquistasRoute = AppConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesRoute = AppCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/cartoes': typeof AppCartoesRoute
  '/app/conquistas': typeof AppConquistasRoute
  '/app/contas': typeof AppContasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/fluxo': typeof AppFluxoRoute
  '/app/metas': typeof AppMetasRoute
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/cartoes': typeof AppCartoesRoute
  '/app/conquistas': typeof AppConquistasRoute
  '/app/contas': typeof AppContasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/fluxo': typeof AppFluxoRoute
  '/app/metas': typeof AppMetasRoute
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/cartoes': typeof AppCartoesRoute
  '/app/conquistas': typeof AppConquistasRoute
  '/app/contas': typeof AppContasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/fluxo': typeof AppFluxoRoute
  '/app/metas': typeof AppMetasRoute
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transacoes': typeof AppTransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/cartoes'
    | '/app/conquistas'
    | '/app/contas'
    | '/app/dashboard'
    | '/app/dividas'
    | '/app/fluxo'
    | '/app/metas'
    | '/app/patrimonio'
    | '/app/relatorios'
    | '/app/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/cartoes'
    | '/app/conquistas'
    | '/app/contas'
    | '/app/dashboard'
    | '/app/dividas'
    | '/app/fluxo'
    | '/app/metas'
    | '/app/patrimonio'
    | '/app/relatorios'
    | '/app/transacoes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/cartoes'
    | '/app/conquistas'
    | '/app/contas'
    | '/app/dashboard'
    | '/app/dividas'
    | '/app/fluxo'
    | '/app/metas'
    | '/app/patrimonio'
    | '/app/relatorios'
    | '/app/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transacoes': {
      id: '/app/transacoes'
      path: '/transacoes'
      fullPath: '/app/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patrimonio': {
      id: '/app/patrimonio'
      path: '/patrimonio'
      fullPath: '/app/patrimonio'
      preLoaderRoute: typeof AppPatrimonioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fluxo': {
      id: '/app/fluxo'
      path: '/fluxo'
      fullPath: '/app/fluxo'
      preLoaderRoute: typeof AppFluxoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dividas': {
      id: '/app/dividas'
      path: '/dividas'
      fullPath: '/app/dividas'
      preLoaderRoute: typeof AppDividasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas': {
      id: '/app/contas'
      path: '/contas'
      fullPath: '/app/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conquistas': {
      id: '/app/conquistas'
      path: '/conquistas'
      fullPath: '/app/conquistas'
      preLoaderRoute: typeof AppConquistasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cartoes': {
      id: '/app/cartoes'
      path: '/cartoes'
      fullPath: '/app/cartoes'
      preLoaderRoute: typeof AppCartoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCartoesRoute: typeof AppCartoesRoute
  AppConquistasRoute: typeof AppConquistasRoute
  AppContasRoute: typeof AppContasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDividasRoute: typeof AppDividasRoute
  AppFluxoRoute: typeof AppFluxoRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPatrimonioRoute: typeof AppPatrimonioRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartoesRoute: AppCartoesRoute,
  AppConquistasRoute: AppConquistasRoute,
  AppContasRoute: AppContasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDividasRoute: AppDividasRoute,
  AppFluxoRoute: AppFluxoRoute,
  AppMetasRoute: AppMetasRoute,
  AppPatrimonioRoute: AppPatrimonioRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTransacoesRoute: AppTransacoesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
