/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransacoesRouteImport } from './routes/app/transacoes'
import { Route as AppRelatoriosRouteImport } from './routes/app/relatorios'
import { Route as AppPrevisaoRouteImport } from './routes/app/previsao'
import { Route as AppParcelamentosRouteImport } from './routes/app/parcelamentos'
import { Route as AppMetasRouteImport } from './routes/app/metas'
import { Route as AppDividasRouteImport } from './routes/app/dividas'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppConquistasRouteImport } from './routes/app/conquistas'
import { Route as AppCartoesRouteImport } from './routes/app/cartoes'
import { Route as AppAssinaturasRouteImport } from './routes/app/assinaturas'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPrevisaoRoute = AppPrevisaoRouteImport.update({
  id: '/previsao',
  path: '/previsao',
  getParentRoute: () => AppRoute,
} as any)
const AppParcelamentosRoute = AppParcelamentosRouteImport.update({
  id: '/parcelamentos',
  path: '/parcelamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppDividasRoute = AppDividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConquistasRoute = AppConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesRoute = AppCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturasRoute = AppAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assinaturas': typeof AppAssinaturasRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/conquistas': typeof AppConquistasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/metas': typeof AppMetasRoute
  '/app/parcelamentos': typeof AppParcelamentosRoute
  '/app/previsao': typeof AppPrevisaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assinaturas': typeof AppAssinaturasRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/conquistas': typeof AppConquistasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/metas': typeof AppMetasRoute
  '/app/parcelamentos': typeof AppParcelamentosRoute
  '/app/previsao': typeof AppPrevisaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assinaturas': typeof AppAssinaturasRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/conquistas': typeof AppConquistasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dividas': typeof AppDividasRoute
  '/app/metas': typeof AppMetasRoute
  '/app/parcelamentos': typeof AppParcelamentosRoute
  '/app/previsao': typeof AppPrevisaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transacoes': typeof AppTransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/assinaturas'
    | '/app/cartoes'
    | '/app/conquistas'
    | '/app/dashboard'
    | '/app/dividas'
    | '/app/metas'
    | '/app/parcelamentos'
    | '/app/previsao'
    | '/app/relatorios'
    | '/app/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/assinaturas'
    | '/app/cartoes'
    | '/app/conquistas'
    | '/app/dashboard'
    | '/app/dividas'
    | '/app/metas'
    | '/app/parcelamentos'
    | '/app/previsao'
    | '/app/relatorios'
    | '/app/transacoes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/assinaturas'
    | '/app/cartoes'
    | '/app/conquistas'
    | '/app/dashboard'
    | '/app/dividas'
    | '/app/metas'
    | '/app/parcelamentos'
    | '/app/previsao'
    | '/app/relatorios'
    | '/app/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transacoes': {
      id: '/app/transacoes'
      path: '/transacoes'
      fullPath: '/app/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/previsao': {
      id: '/app/previsao'
      path: '/previsao'
      fullPath: '/app/previsao'
      preLoaderRoute: typeof AppPrevisaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parcelamentos': {
      id: '/app/parcelamentos'
      path: '/parcelamentos'
      fullPath: '/app/parcelamentos'
      preLoaderRoute: typeof AppParcelamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dividas': {
      id: '/app/dividas'
      path: '/dividas'
      fullPath: '/app/dividas'
      preLoaderRoute: typeof AppDividasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conquistas': {
      id: '/app/conquistas'
      path: '/conquistas'
      fullPath: '/app/conquistas'
      preLoaderRoute: typeof AppConquistasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cartoes': {
      id: '/app/cartoes'
      path: '/cartoes'
      fullPath: '/app/cartoes'
      preLoaderRoute: typeof AppCartoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinaturas': {
      id: '/app/assinaturas'
      path: '/assinaturas'
      fullPath: '/app/assinaturas'
      preLoaderRoute: typeof AppAssinaturasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssinaturasRoute: typeof AppAssinaturasRoute
  AppCartoesRoute: typeof AppCartoesRoute
  AppConquistasRoute: typeof AppConquistasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDividasRoute: typeof AppDividasRoute
  AppMetasRoute: typeof AppMetasRoute
  AppParcelamentosRoute: typeof AppParcelamentosRoute
  AppPrevisaoRoute: typeof AppPrevisaoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssinaturasRoute: AppAssinaturasRoute,
  AppCartoesRoute: AppCartoesRoute,
  AppConquistasRoute: AppConquistasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDividasRoute: AppDividasRoute,
  AppMetasRoute: AppMetasRoute,
  AppParcelamentosRoute: AppParcelamentosRoute,
  AppPrevisaoRoute: AppPrevisaoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTransacoesRoute: AppTransacoesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
